services:
  - type: web
    name: lr1-5
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///app.db
